### ISSUE TITLE
Small warning can be removed

### ISSUE THREAD

**Issue by smourier** [stbrumme/xxhash#2]
Hi,

Thanks for this nice, bloat-free code 👍. I have just one remark at this line: https://github.com/stbrumme/xxhash/blob/master/xxhash64.h#L90

    bufferSize = stop - data;

this generates a warning (at least with MSVC x64) since pointers can be 64-bit (although the code is fine and that will never happen):

    warning C4244: '=': conversion from '__int64' to 'unsigned int', possible loss of data

So you could either defined bufferSize as uint64_t (my choice) or add some cast.

**Comment by stbrumme** [comment]
As far as I know, this is an issue only appearing in a Visual C++ environment because its default `int` is still 32 bit (even on 64 bit).

According to https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-160
> The int and unsigned int types have a size of four bytes. However, portable code should not depend on the size of int because the language standard allows this to be implementation-specific.

Nevertheless, I modified https://github.com/stbrumme/xxhash/blob/master/xxhash64.h such that `bufferSize` is `uint64_t` which could/should be a tiny bit faster on x64 CPUs, too.
#https://github.com/stbrumme/xxhash/commit/c2866db364b6ea3a11933e62235ddc166ba18565

The same problem compiler warning might appear when running xxhash32 in a 64 bit environment - but there's no reason to do that, except for saving a few bytes.
